version: "3"
services:
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: "RecycleIT"
      MYSQL_USER: "admin"
      MYSQL_PASSWORD: "admin"
      MYSQL_ROOT_PASSWORD: "admin"
    ports:
      - "3306:3306"